baseURL: https://hugo-toha.github.io

languageCode: en-us
title: "Ken Eto"
theme: "toha"

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  en:
    languageName: English
    weight: 1

# Control TOC depth
markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  # GitHub repo URL of your site
  gitRepo: https://github.com/hugo-toha/hugo-toha.github.io

  background: "images/back.png"

  darkMode:
    enable: true
    provider: darkreader
    default: system

  newsletter:
    enable: false
  
  logo:
    main: images/icon.png
    inverted: images/icon.png
    favicon: images/icon.png
